version: '3.7'
services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__STORAGE__MIN_AVAILABLE_SPACE: 1073741824
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:
